language: node_js
node_js:
  - "15"

branches:
  only:
    - master

jobs:
  include:
    - stage: npm release
      deploy:
        provider: npm
        email: "bella.fusari@gmail.com"
        api_key: ${env.AUTH_TOKEN}

